repository_type: pipeline

nf_core_version: 3.5.2

lint:
  files_unchanged:
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-osmoflow_logo_light.png
    - docs/images/nf-core-osmoflow_logo_light.png
    - docs/images/nf-core-osmoflow_logo_dark.png
    - assets/email_template.txt
    - docs/README.md
    - assets/sendmail_template.txt
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-osmoflow_logo_light.png
    - docs/images/nf-core-osmoflow_logo_light.png
    - docs/images/nf-core-osmoflow_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
    - assets/multiqc_config.yml

template:
  org: barbarahelena
  name: osmoflow
  description: Screen osmoadaptation genes (ectA/ectB/ectC, betL, kdpA, nhaA) in metagenomic
    reads or assemblies using osmotool
  author: barbarahelena
  version: 0.1.0
  force: false
  outdir: .
  skip_features:
    - igenomes
    - fastqc
    - multiqc
    - gpu
    - rocrate
    - adaptivecard
    - slackreport
    - seqera_platform
  is_nfcore: false
